In [67]:
import pandas as pd
from scipy import stats as stats
import numpy as np

In [68]:
df= pd.read_csv('/content/BuyerRatio_new.csv')

In [69]:
df.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   550   351    480    350

In [70]:
df_table=df.iloc[:,1:6]
df_table

East  West  North  South
0    50   142    131     70
1   550   351    480    350

In [71]:
df_table.values

array([[ 50, 142, 131,  70],
       [550, 351, 480, 350]])

In [72]:
val

(80.27295426602495,
 2.682172557281901e-17,
 3,
 array([[111.01694915,  91.21892655, 113.05225989,  77.71186441],
        [488.98305085, 401.78107345, 497.94774011, 342.28813559]]))

In [73]:
type(val)

tuple

In [74]:
no_of_rows=len(df_table.iloc[0:2,0])
no_of_columns=len(df_table.iloc[0,0:4])
degree_of_f=(no_of_rows-1)*(no_of_columns-1)
print('Degree of Freedom=',degree_of_f)

Degree of Freedom= 3


In [75]:
Expected_value=val[3]

In [76]:
Expected_value

array([[111.01694915,  91.21892655, 113.05225989,  77.71186441],
       [488.98305085, 401.78107345, 497.94774011, 342.28813559]])

In [77]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2/e for o,e in zip(df_table.values,Expected_value)])
chi_square_statestic=chi_square[0]+chi_square[1]
chi_square_statestic

75.83769204761725

In [78]:
critical_value=chi2.ppf(0.95,3)
critical_value

7.814727903251179

In [79]:
if chi_square_statestic >= critical_value:
	print('Dependent (reject H0)')
else:
	print('Independent (cant reject H0)')

Dependent (reject H0)


In [80]:
pvalue=1-chi2.cdf(chi_square_statestic,3)
pvalue

2.220446049250313e-16

In [81]:

if pvalue <= 0.05:
	print('Dependent (reject H0)')
else:
	print('Independent (cant reject H0)')

Dependent (reject H0)
